//
//  NewsfeedPresenter.swift
//  VK NewsFeed App
//
//  Created by asbul on 29.07.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NewsfeedPresentationLogic {
    func presentSomething(response: Newsfeed.Something.Response)
}

class NewsfeedPresenter: NewsfeedPresentationLogic {
    
    weak var viewController: NewsfeedDisplayLogic?
    
    func presentSomething(response: Newsfeed.Something.Response) {
        let viewModel = Newsfeed.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
