//
//  NewsfeedInteractor.swift
//  VK NewsFeed App
//
//  Created by asbul on 29.07.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NewsfeedBusinessLogic {
    func doSomething(request: Newsfeed.Something.Request)
}

protocol NewsfeedDataStore {
    
}

class NewsfeedInteractor: NewsfeedBusinessLogic, NewsfeedDataStore {
    
    var presenter: NewsfeedPresentationLogic?
    var worker: NewsfeedWorker?
    
    func doSomething(request: Newsfeed.Something.Request) {
        worker = NewsfeedWorker()
        worker?.doSomeWork()
        
        let response = Newsfeed.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
